# Generated by Django 3.2.4 on 2021-06-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_option_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oprion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_option',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='options',
            field=models.ManyToManyField(related_name='users_option', through='users.UserOption', to='campaigns.Option'),
        ),
    ]
