# Generated by Django 3.2.4 on 2021-06-17 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_delete_payment'),
        ('users', '0002_delete_userorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useroption', to='campaigns.option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useroption', to='users.user')),
            ],
            options={
                'db_table': 'user_option',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('delivery_request', models.CharField(max_length=128)),
                ('payment_type', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_payment', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to='users.user')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.ManyToManyField(through='users.Payment', to='campaigns.Campaign'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_option',
            field=models.ManyToManyField(through='users.UserOption', to='campaigns.Option'),
        ),
    ]
