# Generated by Django 3.2.4 on 2021-06-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210611_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroption',
            old_name='oprion',
            new_name='option',
        ),
    ]
