# Generated by Django 3.2.4 on 2021-06-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210617_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='orderer_contact',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='orderer_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
