# Generated by Django 3.2.4 on 2021-06-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_option_price'),
        ('users', '0004_auto_20210618_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'payment_option',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_option',
        ),
        migrations.AddField(
            model_name='payment',
            name='option',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_payment', to='campaigns.option'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment',
            field=models.ManyToManyField(through='users.Payment', to='campaigns.Option'),
        ),
        migrations.DeleteModel(
            name='UserOption',
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_option', to='users.payment'),
        ),
    ]
