# Generated by Django 3.2.4 on 2021-06-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210621_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
