# Generated by Django 3.2.4 on 2021-06-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
    ]
