# Generated by Django 3.2.4 on 2021-06-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_option', to='campaigns.campaign'),
        ),
    ]
