# Generated by Django 3.2.4 on 2021-06-11 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210609_0935'),
        ('campaigns', '0003_remove_campaign_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery_request',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='option',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='campaigns.option'),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.DeleteModel(
            name='DeliveryInformation',
        ),
    ]
