# Generated by Django 3.2.4 on 2021-06-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_option_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
