# Generated by Django 3.2.4 on 2021-06-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_payment_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
