# Generated by Django 3.2.4 on 2021-06-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_payment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='option',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='option',
            name='payment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='campaigns.payment'),
        ),
        migrations.AddField(
            model_name='option',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
